import React from 'react';
import { jsPDF } from 'jspdf';

const SianNotification: React.FC = () => {

    const generateAndNotify = () => {
        // Create new PDF document
        const doc = new jsPDF();
        const venueName = "The Grand Venue";
        const date = new Date().toLocaleDateString();

        // -- Header --
        doc.setFontSize(22);
        doc.setTextColor(0, 51, 102); // Dark Blue
        doc.text("Martyn's Law Compliance Report", 20, 20);

        doc.setFontSize(12);
        doc.setTextColor(100);
        doc.text(`Generated by RaaS Platform | Date: ${date}`, 20, 30);

        // -- Venue Details --
        doc.setLineWidth(0.5);
        doc.line(20, 35, 190, 35); // Horizontal line

        doc.setFontSize(16);
        doc.setTextColor(0);
        doc.text("Venue Details", 20, 50);

        doc.setFontSize(12);
        doc.text(`Venue Name: ${venueName}`, 20, 60);
        doc.text(`Capacity: 850 (Enhanced Tier)`, 20, 70);
        doc.text(`Responsible Person: Owner (Simulated)`, 20, 80);

        // -- Compliance Summary --
        doc.setFontSize(16);
        doc.text("Compliance Summary (Standard Tier)", 20, 100);

        doc.setFontSize(12);
        doc.text("1. Evacuation Procedures: [VALIDATED]", 20, 110);
        doc.text("2. Invacuation / Lockdown: [VALIDATED]", 20, 120);
        doc.text("3. Staff Communication: [VALIDATED]", 20, 130);
        doc.text("4. Vulnerability Audit: [COMPLETED]", 20, 140);

        // -- Footer --
        doc.setFontSize(10);
        doc.setTextColor(150);
        doc.text("This document serves as proof of reasonable practicability under the Terrorism (Protection of Premises) Draft Bill.", 20, 270, { maxWidth: 170 });

        // -- Save --
        doc.save("Martyns_Law_Compliance_Report.pdf");

        // Optional: Still open mail client as a hint
        // window.location.href = "mailto:notifications@sia.gov.uk?subject=Compliance%20Report&body=Please%20find%20attached...";
    };

    return (
        <div style={{ padding: '20px', border: '1px solid #ccc', borderRadius: '8px', marginTop: '20px' }}>
            <h2>SIA Notification Bridge (Interim State A)</h2>
            <p>Generate compliant PDF and notify SIA.</p>
            <button
                onClick={generateAndNotify}
                style={{
                    backgroundColor: '#0056b3',
                    color: 'white',
                    padding: '10px 20px',
                    border: 'none',
                    borderRadius: '5px',
                    cursor: 'pointer',
                    fontSize: '16px'
                }}
            >
                Generate Report & Notify SIA
            </button>
        </div>
    );
};

export default SianNotification;
